version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres/data
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672

  celery_beat:
    container_name: celery_beat
    depends_on:
      - app
      - db
      - rabbitmq
    build:
      context: .
    env_file:
      - .env
    command: "celery -A backend beat -l info"

  celery_worker:
    container_name: celery_worker
    depends_on:
      - app
      - db
      - rabbitmq
      - celery_beat
    build:
      context: .
    env_file:
      - .env
    command: "celery -A backend worker -l INFO"

  app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - .:/code
      command: >
        sh -c "python3 manage.py migrate &&
                wait &&
                python3 manage.py loaddata initial.json &&
                wait &&
                python3 manage.py runserver 0.0.0.0:8000"
      env_file:
        - .env
      depends_on:
        - db
