version: '3.9'

services:

  nginx:
    container_name: test_deploy_nginx
    build: ./deploy/nginx
    ports:
        - 8008:80
    depends_on:
        - web

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
    - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  celery_worker:
    container_name: celery_worker
    depends_on:
      - web
      - db
      - redis
      - celery_beat
    image: web-image
    command: "celery -A backend worker -l INFO"

  celery_beat:
    container_name: celery_beat
    depends_on:
      - web
      - db
      - redis
    image: web-image
    command: "celery -A backend beat -l info"

  db:
    image: postgres
    restart: always
    volumes:
    - ./data/db:/var/lib/postgres/data
    ports:
    - 5432:5432

  web:
    build: .
    command: sh -c "pipenv run ./manage.py migrate && wait && pipenv run ./manage.py loaddata initial.json && wait && pipenv run gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
    image: web-image
