# Generated by Django 3.1.7 on 2021-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='critics',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='users',
            field=models.FloatField(),
        ),
    ]
