# Generated by Django 3.1.7 on 2021-03-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210304_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.game'),
        ),
    ]
