# Generated by Django 4.0.4 on 2022-04-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('users', models.FloatField(null=True)),
                ('users_count', models.IntegerField(null=True)),
                ('critics', models.FloatField(null=True)),
                ('critics_count', models.IntegerField(null=True)),
                ('total', models.FloatField(null=True)),
                ('total_count', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='ratings_critics',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ratings_critics_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ratings_users',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ratings_users_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='short_description',
        ),
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.rating'),
        ),
    ]
