# Generated by Django 4.0.4 on 2022-04-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rating_remove_game_ratings_critics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='game.game'),
        ),
        migrations.AlterField(
            model_name='musts',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musts', to='game.game'),
        ),
    ]
