# Generated by Django 4.0.4 on 2022-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
