# Generated by Django 3.1.7 on 2021-06-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('logo', models.URLField()),
                ('description', models.TextField(max_length=2048, null=True)),
                ('genres', models.CharField(default='', max_length=128, null=True)),
                ('platforms', models.CharField(default='', max_length=256, null=True)),
                ('date_release', models.CharField(default='', max_length=64, null=True)),
                ('screenshots', models.TextField(max_length=1024, null=True)),
                ('ratings_users', models.CharField(default='', max_length=64, null=True)),
                ('ratings_users_count', models.CharField(default='', max_length=64, null=True)),
                ('ratings_critics', models.CharField(default='', max_length=64, null=True)),
                ('ratings_critics_count', models.CharField(default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Musts',
                'verbose_name_plural': 'Musts',
            },
        ),
    ]
