# Generated by Django 3.1.7 on 2021-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_musts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
