# Generated by Django 4.0.5 on 2022-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_customuser_avatar_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
